### ISSUE TITLE
Firecracker obsolete?

### ISSUE THREAD

**Issue by ader1990** [bkleiner/ubuntu-firecracker#1]
Hello,

If you can say, what made you use something else than firecracker and what are the alternatives?

Thanks.

**Comment by bkleiner** [comment]
At the time this repository was created i was working on a small api on top of firecracker to mange VMs across different physical nodes.
Then i discovered https://kubevirt.io/ which pretty much did what i wanted and had the additional benefit of integrating with k8s, which i was already using.

All that being said, i still think firecracker takes a great approach and if kubevirt ever decides to add it as a backend, i will be the first to switch back to it.

If you happen to have something to contribute to this repository, pull-requests are very welcome!
